/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardWorkshops_newRouteImport } from './routes/dashboard/workshops_new'
import { Route as DashboardWorkshopsRouteImport } from './routes/dashboard/workshops'
import { Route as DashboardVisibilityRouteImport } from './routes/dashboard/visibility'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMergersRouteImport } from './routes/dashboard/mergers'
import { Route as DashboardFundingRouteImport } from './routes/dashboard/funding'
import { Route as DashboardBroadbandRouteImport } from './routes/dashboard/broadband'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminFundingRouteImport } from './routes/dashboard/admin/funding'
import { Route as DashboardAdminBusinessesRouteImport } from './routes/dashboard/admin/businesses'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkshops_newRoute = DashboardWorkshops_newRouteImport.update({
  id: '/workshops_new',
  path: '/workshops_new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkshopsRoute = DashboardWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVisibilityRoute = DashboardVisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMergersRoute = DashboardMergersRouteImport.update({
  id: '/mergers',
  path: '/mergers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFundingRoute = DashboardFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBroadbandRoute = DashboardBroadbandRouteImport.update({
  id: '/broadband',
  path: '/broadband',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminFundingRoute = DashboardAdminFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminBusinessesRoute =
  DashboardAdminBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/broadband': typeof DashboardBroadbandRoute
  '/dashboard/funding': typeof DashboardFundingRoute
  '/dashboard/mergers': typeof DashboardMergersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/visibility': typeof DashboardVisibilityRoute
  '/dashboard/workshops': typeof DashboardWorkshopsRoute
  '/dashboard/workshops_new': typeof DashboardWorkshops_newRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/businesses': typeof DashboardAdminBusinessesRoute
  '/dashboard/admin/funding': typeof DashboardAdminFundingRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/broadband': typeof DashboardBroadbandRoute
  '/dashboard/funding': typeof DashboardFundingRoute
  '/dashboard/mergers': typeof DashboardMergersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/visibility': typeof DashboardVisibilityRoute
  '/dashboard/workshops': typeof DashboardWorkshopsRoute
  '/dashboard/workshops_new': typeof DashboardWorkshops_newRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/businesses': typeof DashboardAdminBusinessesRoute
  '/dashboard/admin/funding': typeof DashboardAdminFundingRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/broadband': typeof DashboardBroadbandRoute
  '/dashboard/funding': typeof DashboardFundingRoute
  '/dashboard/mergers': typeof DashboardMergersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/visibility': typeof DashboardVisibilityRoute
  '/dashboard/workshops': typeof DashboardWorkshopsRoute
  '/dashboard/workshops_new': typeof DashboardWorkshops_newRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/businesses': typeof DashboardAdminBusinessesRoute
  '/dashboard/admin/funding': typeof DashboardAdminFundingRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/admin'
    | '/auth/verify'
    | '/dashboard/broadband'
    | '/dashboard/funding'
    | '/dashboard/mergers'
    | '/dashboard/profile'
    | '/dashboard/visibility'
    | '/dashboard/workshops'
    | '/dashboard/workshops_new'
    | '/auth'
    | '/dashboard/'
    | '/dashboard/admin/businesses'
    | '/dashboard/admin/funding'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/auth/verify'
    | '/dashboard/broadband'
    | '/dashboard/funding'
    | '/dashboard/mergers'
    | '/dashboard/profile'
    | '/dashboard/visibility'
    | '/dashboard/workshops'
    | '/dashboard/workshops_new'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin/businesses'
    | '/dashboard/admin/funding'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/admin'
    | '/auth/verify'
    | '/dashboard/broadband'
    | '/dashboard/funding'
    | '/dashboard/mergers'
    | '/dashboard/profile'
    | '/dashboard/visibility'
    | '/dashboard/workshops'
    | '/dashboard/workshops_new'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/admin/businesses'
    | '/dashboard/admin/funding'
    | '/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PricingRoute: typeof PricingRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workshops_new': {
      id: '/dashboard/workshops_new'
      path: '/workshops_new'
      fullPath: '/dashboard/workshops_new'
      preLoaderRoute: typeof DashboardWorkshops_newRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/workshops': {
      id: '/dashboard/workshops'
      path: '/workshops'
      fullPath: '/dashboard/workshops'
      preLoaderRoute: typeof DashboardWorkshopsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/visibility': {
      id: '/dashboard/visibility'
      path: '/visibility'
      fullPath: '/dashboard/visibility'
      preLoaderRoute: typeof DashboardVisibilityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/mergers': {
      id: '/dashboard/mergers'
      path: '/mergers'
      fullPath: '/dashboard/mergers'
      preLoaderRoute: typeof DashboardMergersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/funding': {
      id: '/dashboard/funding'
      path: '/funding'
      fullPath: '/dashboard/funding'
      preLoaderRoute: typeof DashboardFundingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/broadband': {
      id: '/dashboard/broadband'
      path: '/broadband'
      fullPath: '/dashboard/broadband'
      preLoaderRoute: typeof DashboardBroadbandRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/funding': {
      id: '/dashboard/admin/funding'
      path: '/funding'
      fullPath: '/dashboard/admin/funding'
      preLoaderRoute: typeof DashboardAdminFundingRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/businesses': {
      id: '/dashboard/admin/businesses'
      path: '/businesses'
      fullPath: '/dashboard/admin/businesses'
      preLoaderRoute: typeof DashboardAdminBusinessesRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface DashboardAdminRouteRouteChildren {
  DashboardAdminBusinessesRoute: typeof DashboardAdminBusinessesRoute
  DashboardAdminFundingRoute: typeof DashboardAdminFundingRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminBusinessesRoute: DashboardAdminBusinessesRoute,
  DashboardAdminFundingRoute: DashboardAdminFundingRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardBroadbandRoute: typeof DashboardBroadbandRoute
  DashboardFundingRoute: typeof DashboardFundingRoute
  DashboardMergersRoute: typeof DashboardMergersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardVisibilityRoute: typeof DashboardVisibilityRoute
  DashboardWorkshopsRoute: typeof DashboardWorkshopsRoute
  DashboardWorkshops_newRoute: typeof DashboardWorkshops_newRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardBroadbandRoute: DashboardBroadbandRoute,
  DashboardFundingRoute: DashboardFundingRoute,
  DashboardMergersRoute: DashboardMergersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardVisibilityRoute: DashboardVisibilityRoute,
  DashboardWorkshopsRoute: DashboardWorkshopsRoute,
  DashboardWorkshops_newRoute: DashboardWorkshops_newRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PricingRoute: PricingRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
